server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd 
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true  #使用数值timestamp表示日期，true时会忽略date-format
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/bpm?stringtype=unspecified&ApplicationName=tutorial
    username: pgdbo
    password: sql
  activiti:
    mail-server-host: smtp.ym.163.com
    mail-server-user-name: user@user.com
    mail-server-password: password
    mail-server-default-from: user@user.com


logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.devmgr: TRACE

