server:
  servlet:
    session:
      timeout: 1800s  #session超时时间，s表示单位是秒
      cookie:         #保存sessionID的cookie
        name: TSESSIONID
        path: /

logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.devmgr: TRACE
    org.springframework: INFO
    org.thymeleaf.TemplateEngine: INFO

spring:
  thymeleaf:
    cache: false